version: '2'
services:

  dev:
    build:
      context: ./
      args:
        ARG_FAKES3_VERSION: ${DOCKER_FAKES3_VERSION}
    image: muccg/fake-s3:${GIT_BRANCH}

  prod:
    build:
      context: ./
      args:
        ARG_FAKES3_VERSION: ${DOCKER_FAKES3_VERSION}
    image: muccg/fake-s3:${DOCKER_FAKES3_VERSION}

  latest:
    extends:
      file: docker-compose-build.yml
      service: prod
    image: muccg/fake-s3:latest
